spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password

spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=POST, GET, OPTIONS, DELETE, PUT
spring.mvc.cors.allowed-headers=Content-Type, X-Requested-With, accept, Origin, Produces
spring.mvc.cors.allow-credentials=true

spring.jpa.hibernate.ddl-auto=update